"""index log filter and ordering columns

Revision ID: 58dc647b3fcb
Revises: b2623131ecea
Created: 2026-08-06 08:38:22.350791
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '58dc647b3fcb'
down_revision = 'b2623131ecea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_files_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_insurer'), ['insurer'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_status'), ['status'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('review_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_flags_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    with op.batch_alter_table('review_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_flags_created_at'))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_created_at'))

    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_status'))
        batch_op.drop_index(batch_op.f('ix_log_entries_insurer'))
        batch_op.drop_index(batch_op.f('ix_log_entries_entry_type'))
        batch_op.drop_index(batch_op.f('ix_log_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_log_entries_client_name'))

    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_created_at'))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_created_at'))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_files_created_at'))

    # ### end Alembic commands ###
