"""index every foreign-key predicate

Revision ID: b2623131ecea
Revises: ed64148106c1
Created: 2026-08-06 08:32:31.816883
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b2623131ecea'
down_revision = 'ed64148106c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_files_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_files_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_files_parent_file_id'), ['parent_file_id'], unique=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_client_policy_id'), ['client_policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_legal_entity_id'), ['legal_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_sub_group_id'), ['sub_group_id'], unique=False)

    with op.batch_alter_table('client_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_policies_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_policies_legal_entity_id'), ['legal_entity_id'], unique=False)

    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_case_id'), ['case_id'], unique=False)

    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_entities_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_principal_member_id'), ['principal_member_id'], unique=False)

    with op.batch_alter_table('review_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_flags_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_flags_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('sub_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_groups_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_groups_client_id'))

    with op.batch_alter_table('review_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_flags_member_id'))
        batch_op.drop_index(batch_op.f('ix_review_flags_case_id'))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_principal_member_id'))
        batch_op.drop_index(batch_op.f('ix_members_case_id'))

    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_member_id'))
        batch_op.drop_index(batch_op.f('ix_log_entries_case_id'))

    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_entities_client_id'))

    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_case_id'))

    with op.batch_alter_table('client_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_policies_legal_entity_id'))
        batch_op.drop_index(batch_op.f('ix_client_policies_client_id'))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_sub_group_id'))
        batch_op.drop_index(batch_op.f('ix_cases_reference'))
        batch_op.drop_index(batch_op.f('ix_cases_owner_id'))
        batch_op.drop_index(batch_op.f('ix_cases_legal_entity_id'))
        batch_op.drop_index(batch_op.f('ix_cases_client_policy_id'))
        batch_op.drop_index(batch_op.f('ix_cases_client_id'))

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_files_parent_file_id'))
        batch_op.drop_index(batch_op.f('ix_case_files_member_id'))
        batch_op.drop_index(batch_op.f('ix_case_files_case_id'))

    # ### end Alembic commands ###
