"""initial schema

Revision ID: ed64148106c1
Revises:
Created: 2026-08-05 16:40:44.732056
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ed64148106c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('log_associate', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('legal_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('contract_name', sa.String(length=191), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_entity_per_client')
    )
    op.create_table('sub_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('emirate', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_sub_group_per_client')
    )
    op.create_table('client_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('legal_entity_id', sa.String(length=36), nullable=True),
    sa.Column('insurer', sa.String(length=128), nullable=False),
    sa.Column('network', sa.String(length=128), nullable=True),
    sa.Column('policy_no', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('emirate', sa.String(length=32), nullable=True),
    sa.Column('addition_template_key', sa.String(length=64), nullable=True),
    sa.Column('deletion_template_key', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('sub_group_id', sa.String(length=36), nullable=True),
    sa.Column('legal_entity_id', sa.String(length=36), nullable=True),
    sa.Column('client_policy_id', sa.String(length=36), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=False),
    sa.Column('sub_group', sa.String(length=128), nullable=True),
    sa.Column('legal_entity', sa.String(length=191), nullable=True),
    sa.Column('insurer', sa.String(length=128), nullable=False),
    sa.Column('policy_no', sa.String(length=64), nullable=True),
    sa.Column('contract_name', sa.String(length=191), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=True),
    sa.Column('email_subject', sa.String(length=512), nullable=True),
    sa.Column('email_received_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('bms_comments', sa.Text(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['client_policy_id'], ['client_policies.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_group_id'], ['sub_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_ok', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('recalculated', sa.Boolean(), nullable=False),
    sa.Column('recalc_detail', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('marital_status', sa.String(length=32), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('passport_no', sa.String(length=64), nullable=True),
    sa.Column('passport_expiry', sa.String(length=32), nullable=True),
    sa.Column('emirates_id', sa.String(length=32), nullable=True),
    sa.Column('unified_no', sa.String(length=32), nullable=True),
    sa.Column('visa_file_number', sa.String(length=64), nullable=True),
    sa.Column('birth_certificate_number', sa.String(length=64), nullable=True),
    sa.Column('staff_id', sa.String(length=64), nullable=True),
    sa.Column('relation', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('contract_name', sa.String(length=191), nullable=True),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('member_card_no', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=64), nullable=True),
    sa.Column('cancellation_date', sa.String(length=32), nullable=True),
    sa.Column('principal_member_id', sa.String(length=36), nullable=True),
    sa.Column('principal_card_no', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile_no', sa.String(length=64), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['principal_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('archive_path', sa.String(length=1024), nullable=True),
    sa.Column('parent_file_id', sa.String(length=36), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scan_verdict', sa.String(length=24), nullable=False),
    sa.Column('scan_detail', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=48), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('manually_classified', sa.Boolean(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('text_source', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['parent_file_id'], ['case_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_files_sha256'), ['sha256'], unique=False)

    op.create_table('log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('shared_by', sa.String(length=64), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('sub_group', sa.String(length=128), nullable=True),
    sa.Column('insurer', sa.String(length=128), nullable=True),
    sa.Column('policy_no', sa.String(length=64), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=191), nullable=True),
    sa.Column('relation', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('staff_id', sa.String(length=64), nullable=True),
    sa.Column('emirates_id', sa.String(length=32), nullable=True),
    sa.Column('entry_type', sa.String(length=48), nullable=True),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('request_receive_date', sa.String(length=32), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('remarks2', sa.Text(), nullable=True),
    sa.Column('request_ref_no', sa.String(length=128), nullable=True),
    sa.Column('request_sent_date_to_insurer', sa.String(length=32), nullable=True),
    sa.Column('card_no', sa.String(length=64), nullable=True),
    sa.Column('card_receive_and_sent_date', sa.String(length=32), nullable=True),
    sa.Column('saiba_voucher_no', sa.String(length=64), nullable=True),
    sa.Column('bbm_invoice_date', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('raw_value', sa.String(length=512), nullable=True),
    sa.Column('normalised_value', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=48), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['case_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_fields')
    op.drop_table('review_flags')
    op.drop_table('log_entries')
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_files_sha256'))

    op.drop_table('case_files')
    op.drop_table('members')
    op.drop_table('exports')
    op.drop_table('cases')
    op.drop_table('client_policies')
    op.drop_table('sub_groups')
    op.drop_table('legal_entities')
    op.drop_table('users')
    op.drop_table('clients')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
