"""NAS addition and deletion output.

Builds template rows from approved member records and hands them to the
registry's surgical writer, which regenerates from a fresh master and blocks
release on any structural change.

Only approved members are exported, and only when no critical flag is open.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from ..models import Member, TransactionType
from ..registry.generate import generate
from ..templates.specs import (
    NAS_ALDAR_ADDITION,
    NAS_DELETION,
    NAS_IFFCO_ADDITION,
    SPECS_BY_KEY,
    TemplateSpec,
)
from .mapping import for_template

# Templates this phase supports end to end.
SUPPORTED_KEYS = (
    NAS_ALDAR_ADDITION.key,
    NAS_IFFCO_ADDITION.key,
    NAS_DELETION.key,
)


class UnsupportedTemplate(Exception):
    pass


@dataclass
class BuiltRows:
    spec: TemplateSpec
    rows: list[dict]
    skipped: list[tuple[str, str]]


def _addition_row(member: Member, value_map, attachments: dict | None = None) -> dict:
    """One NAS addition row.

    Fields BMS confirmed are left blank stay absent from the dict entirely, so
    the writer never puts anything in those cells. Department and Grade are
    blank by instruction; Occupation is blank because it is not mandatory for
    the NAS process.
    """
    row: dict[str, object] = {
        "contract_name": member.contract_name,
        "first_name": member.first_name,
        "middle_name": member.middle_name,
        "last_name": member.last_name,
        "effective_date": value_map.render_date(member.effective_date),
        "date_of_birth": value_map.render_date(member.date_of_birth),
        "gender": value_map.render("gender", member.gender),
        "marital_status": value_map.render("marital_status", member.marital_status),
        "category": member.category,
        "relation": value_map.render("relation", member.relation),
        "staff_id": member.staff_id,
        "nationality": member.nationality,
        "emirates_id": member.emirates_id,
        "unified_no": member.unified_no,
        "passport_no": member.passport_no,
        "email": member.email,
        "mobile_no": member.mobile_no,
        "visa_file_number": member.visa_file_number,
        "birth_certificate_number": member.birth_certificate_number,
        "passport_expiry_date": value_map.render_date(member.passport_expiry),
        "principal_card_no": member.principal_card_no,
    }

    # Attachment columns must carry the exact filename present in the ZIP -- NAS
    # matches documents by name, so these are generated by the packager rather
    # than typed, and written back here.
    if attachments:
        row["member_photo"] = attachments.get("photo")
        row["medical_declaration_file"] = attachments.get("declaration")

    return {key: value for key, value in row.items() if value not in (None, "")}


def _deletion_row(member: Member, value_map) -> dict:
    row: dict[str, object] = {
        "member_card_no": member.member_card_no,
        "emirates_id": member.emirates_id,
        "effective_date": value_map.render_date(member.effective_date),
        "deletion_reason": member.deletion_reason,
    }
    return {key: value for key, value in row.items() if value not in (None, "")}


def build_rows(
    template_key: str,
    members: Iterable[Member],
    *,
    attachments: dict[str, dict] | None = None,
) -> BuiltRows:
    """Turn approved members into template rows.

    `attachments` maps member id -> {"photo": name, "declaration": name} as
    produced by the supporting-document packager.
    """
    if template_key not in SUPPORTED_KEYS:
        raise UnsupportedTemplate(
            f"{template_key} is not wired up in this phase. Supported: {', '.join(SUPPORTED_KEYS)}"
        )
    spec = SPECS_BY_KEY[template_key]
    value_map = for_template(template_key)
    is_deletion = spec.key == NAS_DELETION.key

    rows: list[dict] = []
    skipped: list[tuple[str, str]] = []

    for member in members:
        if not member.approved:
            skipped.append((member.id, "member is not approved"))
            continue
        expected = (
            TransactionType.DELETION.value if is_deletion else TransactionType.ADDITION.value
        )
        if member.transaction_type != expected:
            skipped.append((member.id, f"member is a {member.transaction_type}, not a {expected}"))
            continue
        if is_deletion:
            rows.append(_deletion_row(member, value_map))
        else:
            rows.append(
                _addition_row(member, value_map, (attachments or {}).get(member.id))
            )

    return BuiltRows(spec=spec, rows=rows, skipped=skipped)


def generate_workbook(
    template_key: str,
    members: Iterable[Member],
    *,
    repo_root: str | Path,
    output: str | Path,
    attachments: dict[str, dict] | None = None,
) -> BuiltRows:
    """Build the rows and write the portal workbook.

    Raises `StructuralDrift` from the registry if the produced file differs
    structurally from its master, in which case nothing is released.
    """
    built = build_rows(template_key, members, attachments=attachments)
    generate(built.spec, built.rows, repo_root=repo_root, output=output)
    return built
